-- CHAMP schema extension for structured diagnosis, medicine catalog, and recovery outcomes.
-- Apply manually to an existing PostgreSQL database. This script does not drop or rewrite data.

CREATE TABLE IF NOT EXISTS medicine_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_name VARCHAR(255) NOT NULL,
    active_ingredient VARCHAR(255),
    strength VARCHAR(100),
    dosage_form VARCHAR(100),
    atc_code VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS diagnosis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis_code VARCHAR(50),
    diagnosis_name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT uk_diagnosis_code UNIQUE (diagnosis_code)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS doctor_otp_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE users SET doctor_otp_notifications_enabled = TRUE WHERE doctor_otp_notifications_enabled IS NULL;
ALTER TABLE users ALTER COLUMN doctor_otp_notifications_enabled SET DEFAULT TRUE;
ALTER TABLE users ALTER COLUMN doctor_otp_notifications_enabled SET NOT NULL;

CREATE TABLE IF NOT EXISTS doctor_patient_access_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_user_id BIGINT NOT NULL REFERENCES users(id),
    patient_user_id BIGINT NOT NULL REFERENCES users(id),
    otp VARCHAR(6) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    purpose VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS idx_access_doctor_patient_status ON doctor_patient_access_request (doctor_user_id, patient_user_id, status);

CREATE TABLE IF NOT EXISTS patient_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_user_id BIGINT NOT NULL REFERENCES users(id),
    access_request_id BIGINT,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    otp VARCHAR(6),
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_patient_notification_patient_created ON patient_notification (patient_user_id, created_at DESC);

ALTER TABLE visit ADD COLUMN IF NOT EXISTS diagnosis_id BIGINT;
ALTER TABLE visit ADD COLUMN IF NOT EXISTS recovery_status VARCHAR(30);
ALTER TABLE visit ADD COLUMN IF NOT EXISTS recovery_confirmed_at TIMESTAMP;
ALTER TABLE visit ADD COLUMN IF NOT EXISTS outcome_source VARCHAR(50);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS medicine_id BIGINT;
ALTER TABLE allergy ADD COLUMN IF NOT EXISTS allergy_type VARCHAR(30);

UPDATE allergy
SET allergy_type = 'NONE'
WHERE LOWER(TRIM(title)) = 'no known allergy';

UPDATE allergy
SET allergy_type = 'ENVIRONMENTAL'
WHERE LOWER(TRIM(title)) = 'dust allergy';

UPDATE allergy
SET allergy_type = 'SEASONAL'
WHERE LOWER(TRIM(title)) = 'seasonal allergy';

UPDATE allergy
SET allergy_type = 'OTHER'
WHERE allergy_type IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_visit_diagnosis'
    ) THEN
        ALTER TABLE visit
            ADD CONSTRAINT fk_visit_diagnosis
            FOREIGN KEY (diagnosis_id) REFERENCES diagnosis(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_medicine_catalog'
    ) THEN
        ALTER TABLE medicine
            ADD CONSTRAINT fk_medicine_catalog
            FOREIGN KEY (medicine_id) REFERENCES medicine_catalog(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_visit_diagnosis_id ON visit (diagnosis_id);
CREATE INDEX IF NOT EXISTS idx_medicine_catalog_id ON medicine (medicine_id);
CREATE INDEX IF NOT EXISTS idx_allergy_type ON allergy (allergy_type);
