spring.application.name=champ

spring.datasource.url=jdbc:postgresql://localhost:5432/champ
spring.datasource.username=postgres
spring.datasource.password=1311

ml.service.base-url=http://localhost:8000
ml.service.medicine-success-path=/api/v1/predictions/medicine-success
ml.service.recovery-path=/api/v1/predictions/recovery-time
ml.service.safety-path=/api/v1/safety/check
ml.service.connect-timeout-ms=5000
ml.service.read-timeout-ms=10000
champ.access.otp-expiration-minutes=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
